language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
before_script:
  # --prefer-dist causes composer to download zip files (as opposed to cloning git repos which is much slower)
  - composer install --prefer-dist
script:
  - vendor/bin/behat
